import { StyleSheet } from 'react-native';
import { IOS_COLORS } from '../../theme/paperTheme';

export const deliveryFailStyles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: IOS_COLORS.fillMedium,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  title: { fontSize: 18, fontWeight: '700', color: IOS_COLORS.label },
  sub: { marginTop: 3, fontSize: 13, color: IOS_COLORS.labelSecondary },
  hint: {
    marginTop: 10,
    fontSize: 12,
    color: IOS_COLORS.labelSecondary,
    fontWeight: '600',
  },
  reasonWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  reasonChip: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: IOS_COLORS.fillLight,
  },
  reasonChipActive: { backgroundColor: '#FDECEC' },
  reasonChipText: { fontSize: 12, color: IOS_COLORS.labelSecondary, fontWeight: '600' },
  reasonChipTextActive: { color: IOS_COLORS.red },
  inputBox: {
    marginTop: 10,
    borderRadius: 12,
    backgroundColor: IOS_COLORS.fillLight,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  input: {
    minHeight: 44,
    color: IOS_COLORS.label,
    fontSize: 14,
    lineHeight: 20,
    textAlignVertical: 'top',
  },
  actions: { flexDirection: 'row', gap: 10, marginTop: 12 },
  cancelBtn: {
    flex: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(118,118,128,0.12)',
    paddingVertical: 12,
  },
  cancelBtnText: { fontSize: 14, fontWeight: '600', color: IOS_COLORS.label },
  confirmBtn: {
    flex: 1.4,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: IOS_COLORS.red,
    paddingVertical: 12,
  },
  confirmBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
});
