import { StyleSheet } from 'react-native';
import { IOS_COLORS } from '../../theme/paperTheme';

export const entryStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: IOS_COLORS.card,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: IOS_COLORS.separatorLight,
  },
  cancel: { fontSize: 17, color: IOS_COLORS.labelSecondary },
  title: { fontSize: 17, fontWeight: '600', color: IOS_COLORS.label },
  confirm: { fontSize: 17, color: IOS_COLORS.blue, fontWeight: '600' },

  /** 上：会员餐/散餐 + 录入日期；下：模式说明（给下面凭证区留全宽） */
  modeRow: {
    flexDirection: 'column',
    backgroundColor: IOS_COLORS.card,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: IOS_COLORS.separatorLight,
    gap: 8,
  },
  modeRowInner: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    width: '100%',
  },
  /** 录入日期紧挨模式切换，占满右侧剩余宽度，与左侧分段同高 */
  modeDateWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  /** 与 modeGroup 同高，避免上下错缝 */
  modeRowDatePicker: {
    flex: 1,
    minHeight: 44,
    alignSelf: 'stretch',
  },
  modeGroup: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: IOS_COLORS.fillMedium,
    borderRadius: 10,
    padding: 3,
    flexShrink: 0,
    alignSelf: 'stretch',
    minHeight: 44,
  },
  modeBtn: {
    paddingHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    minWidth: 76,
  },
  modeBtnActive: { backgroundColor: IOS_COLORS.card },
  modeBtnText: { fontSize: 16, color: IOS_COLORS.labelSecondary },
  modeBtnTextActive: { color: IOS_COLORS.label, fontWeight: '600' },
  modeHint: { fontSize: 12, color: IOS_COLORS.labelTertiary, lineHeight: 17 },

  scroll: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 40 },

  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: IOS_COLORS.labelSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 8,
    paddingLeft: 4,
  },

  /** 仅订餐凭证：全宽卡片（录入日期已移到顶部模式行） */
  proofCard: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 16,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(17,17,17,0.06)',
  },
  proofCardTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: IOS_COLORS.labelSecondary,
    marginBottom: 8,
    letterSpacing: 0.2,
  },

  searchBox: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 2,
    marginBottom: 10,
  },
  searchInput: {
    fontSize: 15,
    color: IOS_COLORS.label,
    paddingVertical: 10,
  },

  memberList: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 4,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: IOS_COLORS.separatorLight,
  },
  memberRowLast: { borderBottomWidth: 0 },
  memberAvatar: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  memberAvatarText: { fontSize: 15, fontWeight: '600', color: IOS_COLORS.blue },
  memberName: { fontSize: 15, fontWeight: '600', color: IOS_COLORS.label },
  memberNick: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 1 },
  memberCardBadge: {
    fontSize: 12,
    color: IOS_COLORS.blue,
    backgroundColor: IOS_COLORS.blueLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  memberNoCard: {
    fontSize: 11,
    color: IOS_COLORS.red,
    backgroundColor: '#FFE5E5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: '600',
  },

  warnBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFF0F0',
    borderColor: '#FFD2D2',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 10,
  },
  warnTitle: { fontSize: 14, fontWeight: '700', color: IOS_COLORS.red },
  warnHint: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 2, lineHeight: 16 },
  warnCta: {
    backgroundColor: IOS_COLORS.red,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  warnCtaText: { color: '#fff', fontSize: 13, fontWeight: '700' },

  selectedMemberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: IOS_COLORS.blueLight,
    borderRadius: 14,
    padding: 14,
    marginBottom: 4,
  },

  searchHintSpacer: { height: 4 },
  dropdownEmpty: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 18,
    alignItems: 'center',
  },
  dropdownEmptyText: { fontSize: 13, color: IOS_COLORS.labelSecondary },
  selAvatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  selAvatarText: { fontSize: 18, fontWeight: '700', color: IOS_COLORS.blue },
  selName: { fontSize: 15, fontWeight: '600', color: IOS_COLORS.label },
  selSub: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 2 },
  selDiet: { fontSize: 12, color: IOS_COLORS.orange, marginTop: 2 },
  changeBtn: { fontSize: 15, color: IOS_COLORS.blue },

  divider: { height: StyleSheet.hairlineWidth, backgroundColor: IOS_COLORS.separatorLight, marginVertical: 16 },

  qtySection: { backgroundColor: IOS_COLORS.card, borderRadius: 14, overflow: 'hidden', marginBottom: 4 },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: IOS_COLORS.separatorLight,
  },
  qtyLabel: { fontSize: 15, color: IOS_COLORS.label, fontWeight: '500' },
  qtyControls: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  qtyBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: IOS_COLORS.blue, alignItems: 'center', justifyContent: 'center' },
  qtyBtnDisabled: { backgroundColor: IOS_COLORS.fillMedium },
  qtyBtnText: { fontSize: 20, color: '#fff', fontWeight: '500', lineHeight: 24 },
  qtyValue: { fontSize: 20, fontWeight: '700', color: IOS_COLORS.label, minWidth: 32, textAlign: 'center' },

  notesBox: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 4,
    marginTop: 12,
  },
  notesInput: { fontSize: 15, color: IOS_COLORS.label, paddingVertical: 10, minHeight: 60 },
  dateCard: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 6,
  },
  dateHint: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    marginBottom: 16,
    paddingLeft: 4,
  },

  inlineCard: { backgroundColor: IOS_COLORS.card, borderRadius: 14, overflow: 'hidden' },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  fieldRowTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  fieldDivider: { height: StyleSheet.hairlineWidth, backgroundColor: IOS_COLORS.separatorLight, marginLeft: 16 },
  fieldLabel: { fontSize: 15, color: IOS_COLORS.label },
  fieldRequired: { color: IOS_COLORS.red, fontWeight: '700' },
  fieldInput: { fontSize: 15, color: IOS_COLORS.label, flex: 1, textAlign: 'right', paddingLeft: 8 },
  fieldInputMulti: {
    textAlign: 'right',
    minHeight: 44,
    lineHeight: 20,
    paddingTop: 4,
  },
  hintUnderCard: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    paddingHorizontal: 20,
    paddingTop: 6,
  },

  /** Switch 行：主标题 + 灰色说明（贴 iOS 设置项） */
  switchLabelCol: { flex: 1, paddingRight: 12 },
  switchHint: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    marginTop: 4,
    lineHeight: 16,
  },

  adhocTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: IOS_COLORS.blueLight,
    borderRadius: 14,
    marginTop: 10,
  },
  adhocTotalLabel: { fontSize: 15, color: IOS_COLORS.blue },
  adhocTotalValue: { fontSize: 24, fontWeight: '700', color: IOS_COLORS.blue },

  submitBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  submitMain: { fontSize: 15, fontWeight: '700', color: IOS_COLORS.label },
  submitSub: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 2 },
  submitHint: { fontSize: 13, color: IOS_COLORS.labelTertiary },
  submitBtn: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: IOS_COLORS.blue,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 110,
  },
  submitBtnRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  submitBtnSecondary: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: IOS_COLORS.fillMedium,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: IOS_COLORS.separatorLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitBtnSecondaryDisabled: { opacity: 0.45 },
  submitBtnSecondaryText: { color: IOS_COLORS.label, fontSize: 14, fontWeight: '600' },
  submitBtnDisabled: { backgroundColor: IOS_COLORS.labelTertiary },
  submitBtnText: { color: '#fff', fontSize: 15, fontWeight: '700', lineHeight: 15 },

  toast: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 80,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(52,199,89,0.94)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  toastText: { color: '#fff', fontSize: 14, fontWeight: '600', flex: 1 },
  toastLink: { color: '#fff', fontSize: 13, fontWeight: '700', textDecorationLine: 'underline' },
});
