import { Platform, StyleSheet } from 'react-native';
import { IOS_COLORS } from '../../theme/paperTheme';

export const entryStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: IOS_COLORS.card,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: IOS_COLORS.separatorLight,
  },
  cancel: { fontSize: 17, color: IOS_COLORS.labelSecondary },
  title: { fontSize: 17, fontWeight: '600', color: IOS_COLORS.label },
  confirm: { fontSize: 17, color: IOS_COLORS.blue, fontWeight: '600' },

  /** 模式区外层：透明，与 ScrollView 内卡片同边距 */
  modeRowShell: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 6,
  },
  /** 与 formCard 叠用：仅纵向排版 */
  modeRow: {
    flexDirection: 'column',
    gap: 6,
  },
  modeRowInner: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    width: '100%',
  },
  /** 录入日期紧挨模式切换，占满右侧剩余宽度，与左侧分段同高 */
  modeDateWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  /** 与 modeGroup 同高，避免上下错缝 */
  modeRowDatePicker: {
    flex: 1,
    minWidth: 0,
    width: '100%',
    minHeight: 44,
    alignSelf: 'stretch',
  },
  modeGroup: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: IOS_COLORS.fillMedium,
    borderRadius: 10,
    padding: 3,
    flexShrink: 0,
    alignSelf: 'stretch',
    minHeight: 44,
  },
  modeBtn: {
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    minWidth: 72,
  },
  modeBtnActive: { backgroundColor: IOS_COLORS.card },
  modeBtnText: {
    fontSize: 15,
    color: IOS_COLORS.labelSecondary,
    ...(Platform.OS === 'web' ? ({ whiteSpace: 'nowrap' } as object) : {}),
  },
  modeBtnTextActive: { color: IOS_COLORS.label, fontWeight: '600' },
  modeHint: { fontSize: 12, color: IOS_COLORS.labelTertiary, lineHeight: 16 },

  scroll: { paddingHorizontal: 14, paddingTop: 4, paddingBottom: 24, gap: 10 },

  /** 分组白卡片（搜索 / 份数 / 凭证等） */
  formCard: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(17,17,17,0.06)',
    gap: 10,
  },
  cardSectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: IOS_COLORS.label,
    marginBottom: 2,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  cardTitleRowTitle: {
    flex: 1,
    minWidth: 0,
    marginBottom: 0,
  },
  cardTitleSwitch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  cardTitleSwitchLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: IOS_COLORS.labelSecondary,
  },
  cardSectionHint: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    lineHeight: 16,
    marginBottom: 4,
  },

  batchSearchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  batchCountPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: IOS_COLORS.blueLight,
  },
  batchCountPillEmpty: {
    backgroundColor: IOS_COLORS.fillLight,
  },
  batchCountText: {
    fontSize: 14,
    fontWeight: '700',
    color: IOS_COLORS.blue,
  },
  batchCountTextEmpty: {
    color: IOS_COLORS.labelSecondary,
    fontWeight: '600',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: IOS_COLORS.fillLight,
    borderRadius: 10,
    paddingHorizontal: 10,
    minHeight: 44,
  },
  searchRowIcon: { marginTop: 1 },
  memberListInCard: {
    marginTop: 4,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: IOS_COLORS.separatorLight,
  },
  batchRosterList: {
    gap: 0,
  },
  batchRosterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  batchRosterName: {
    fontSize: 15,
    fontWeight: '600',
    color: IOS_COLORS.label,
  },
  batchRosterMeta: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    marginTop: 2,
  },
  batchQtyBlock: {
    gap: 8,
    paddingVertical: 6,
  },
  batchQtyName: {
    fontSize: 14,
    fontWeight: '600',
    color: IOS_COLORS.label,
  },

  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: IOS_COLORS.labelSecondary,
    letterSpacing: 0.3,
    marginBottom: 6,
    paddingLeft: 2,
  },

  optionPillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 2,
  },
  optionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: IOS_COLORS.fillLight,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: IOS_COLORS.separatorLight,
  },
  optionPillOn: {
    backgroundColor: IOS_COLORS.blueLight,
    borderColor: 'rgba(0,122,255,0.35)',
  },
  optionPillText: { fontSize: 14, fontWeight: '600', color: IOS_COLORS.labelSecondary },
  optionPillTextOn: { color: IOS_COLORS.blue },

  proofInlineCard: {
    gap: 8,
  },
  proofInlineTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: IOS_COLORS.label,
  },
  proofInlineHint: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    marginTop: 2,
  },

  searchBox: {
    backgroundColor: IOS_COLORS.fillLight,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginBottom: 0,
  },
  searchInput: {
    fontSize: 15,
    color: IOS_COLORS.label,
    paddingVertical: 10,
  },

  memberList: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 4,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: IOS_COLORS.separatorLight,
  },
  memberRowLast: { borderBottomWidth: 0 },
  memberAvatar: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  memberAvatarText: { fontSize: 15, fontWeight: '600', color: IOS_COLORS.blue },
  memberName: { fontSize: 15, fontWeight: '600', color: IOS_COLORS.label },
  memberNick: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 1 },
  memberContact: {
    fontSize: 11,
    color: IOS_COLORS.labelTertiary,
    marginTop: 2,
  },
  /** 含多行联系方式时，整行垂直居中（加号 / 头像 / 右侧标签与正文块对齐） */
  memberRowWithContact: { alignItems: 'center' },
  memberCardBadge: {
    fontSize: 12,
    color: IOS_COLORS.blue,
    backgroundColor: IOS_COLORS.blueLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  memberNoCard: {
    fontSize: 11,
    color: IOS_COLORS.red,
    backgroundColor: '#FFE5E5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: '600',
  },

  warnBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFF0F0',
    borderColor: '#FFD2D2',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 10,
  },
  warnTitle: { fontSize: 14, fontWeight: '700', color: IOS_COLORS.red },
  warnHint: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 2, lineHeight: 16 },
  warnCta: {
    backgroundColor: IOS_COLORS.red,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  warnCtaText: { color: '#fff', fontSize: 13, fontWeight: '700' },

  selectedMemberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: IOS_COLORS.blueLight,
    borderRadius: 12,
    padding: 10,
    marginTop: 4,
  },

  searchHintSpacer: { height: 4 },
  dropdownEmpty: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 18,
    alignItems: 'center',
  },
  dropdownEmptyText: { fontSize: 13, color: IOS_COLORS.labelSecondary },
  selAvatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  selAvatarText: { fontSize: 18, fontWeight: '700', color: IOS_COLORS.blue },
  selName: { fontSize: 15, fontWeight: '600', color: IOS_COLORS.label },
  selSub: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 2 },
  selDiet: { fontSize: 12, color: IOS_COLORS.orange, marginTop: 2 },
  changeBtn: { fontSize: 15, color: IOS_COLORS.blue },

  /** 批量已加入卡片：左信息右删除，紧凑 */
  batchCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingLeft: 12,
    paddingRight: 8,
    gap: 6,
  },
  batchCardBody: { flex: 1, minWidth: 0, gap: 3 },
  /** 姓名 + 卡信息同一行（窄屏自动换行） */
  batchCardTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    columnGap: 8,
    rowGap: 2,
  },
  batchCardName: { fontSize: 14, lineHeight: 18, flexShrink: 1, minWidth: 56 },
  batchCardMetaInline: {
    textAlign: 'left',
    marginTop: 0,
    marginBottom: 0,
    paddingLeft: 0,
    fontSize: 11,
    lineHeight: 14,
    color: IOS_COLORS.labelSecondary,
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  batchCardDelete: { padding: 4 },
  batchCardContact: {
    textAlign: 'left',
    marginTop: 1,
    marginBottom: 0,
    paddingLeft: 0,
    fontSize: 11,
    lineHeight: 14,
    color: IOS_COLORS.labelTertiary,
  },
  batchCardDivider: { marginLeft: 0 },

  divider: { height: StyleSheet.hairlineWidth, backgroundColor: IOS_COLORS.separatorLight, marginVertical: 10 },
  inCardDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: IOS_COLORS.separatorLight,
    marginVertical: 4,
  },

  qtyPairCard: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 4,
  },
  /** 嵌在 formCard 内，避免白底叠白底 */
  qtyPairCardInForm: {
    backgroundColor: IOS_COLORS.fillLight,
    borderRadius: 10,
    marginBottom: 0,
  },
  qtyPairCol: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  qtyPairCaption: {
    fontSize: 12,
    color: IOS_COLORS.labelSecondary,
    marginBottom: 6,
    fontWeight: '500',
  },
  qtyPairVBar: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    backgroundColor: IOS_COLORS.separatorLight,
    marginVertical: 8,
  },
  /** 批量已加入卡片内午/晚更紧凑 */
  qtyPairCardDense: { marginBottom: 0 },
  qtyPairColDense: { paddingVertical: 5, paddingHorizontal: 2 },
  qtyPairCaptionDense: { fontSize: 10, marginBottom: 3 },
  qtyPairVBarDense: { marginVertical: 4 },
  qtyControls: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  qtyBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: IOS_COLORS.blue, alignItems: 'center', justifyContent: 'center' },
  qtyBtnSm: { width: 32, height: 32, borderRadius: 16, backgroundColor: IOS_COLORS.blue, alignItems: 'center', justifyContent: 'center' },
  qtyBtnDisabled: { backgroundColor: IOS_COLORS.fillMedium },
  qtyBtnText: { fontSize: 20, color: '#fff', fontWeight: '500', lineHeight: 24 },
  qtyBtnTextSm: { fontSize: 18, color: '#fff', fontWeight: '500', lineHeight: 22 },
  qtyValue: { fontSize: 20, fontWeight: '700', color: IOS_COLORS.label, minWidth: 32, textAlign: 'center' },
  qtyValueSm: { fontSize: 18, fontWeight: '700', color: IOS_COLORS.label, minWidth: 28, textAlign: 'center' },
  qtyControlsCompact: { flexDirection: 'row', alignItems: 'center', gap: 8 },

  notesBox: {
    backgroundColor: IOS_COLORS.fillLight,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 2,
    marginTop: 0,
  },
  notesInput: { fontSize: 15, color: IOS_COLORS.label, paddingVertical: 10, minHeight: 44 },
  dateCard: {
    backgroundColor: IOS_COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 6,
  },
  dateHint: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    marginBottom: 16,
    paddingLeft: 4,
  },
  dateHintTight: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    lineHeight: 16,
    marginBottom: 0,
    paddingLeft: 0,
  },

  fieldRowEmbedded: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
    gap: 8,
  },
  fieldDividerEmbedded: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: IOS_COLORS.separatorLight,
    marginVertical: 6,
  },

  inlineCard: { backgroundColor: IOS_COLORS.card, borderRadius: 14, overflow: 'hidden' },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  fieldRowTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  fieldDivider: { height: StyleSheet.hairlineWidth, backgroundColor: IOS_COLORS.separatorLight, marginLeft: 16 },
  fieldLabel: { fontSize: 15, color: IOS_COLORS.label },
  fieldRequired: { color: IOS_COLORS.red, fontWeight: '700' },
  fieldInput: { fontSize: 15, color: IOS_COLORS.label, flex: 1, textAlign: 'right', paddingLeft: 8 },
  fieldInputMulti: {
    textAlign: 'right',
    minHeight: 44,
    lineHeight: 20,
    paddingTop: 4,
  },
  hintUnderCard: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    paddingHorizontal: 20,
    paddingTop: 6,
  },

  /** Switch 行：主标题 + 灰色说明（贴 iOS 设置项） */
  switchLabelCol: { flex: 1, paddingRight: 12 },
  switchHint: {
    fontSize: 12,
    color: IOS_COLORS.labelTertiary,
    marginTop: 4,
    lineHeight: 16,
  },

  adhocTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: IOS_COLORS.blueLight,
    borderRadius: 14,
    marginTop: 10,
  },
  adhocTotalLabel: { fontSize: 15, color: IOS_COLORS.blue },
  adhocTotalValue: { fontSize: 24, fontWeight: '700', color: IOS_COLORS.blue },

  submitBarShell: {
    paddingHorizontal: 14,
    paddingTop: 4,
    paddingBottom: 4,
  },
  submitBarCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
      },
      android: { elevation: 6 },
      default: {},
    }),
    ...(Platform.OS === 'web'
      ? ({
          boxShadow: '0 4px 20px rgba(0,0,0,0.08), 0 1px 6px rgba(0,0,0,0.05)',
        } as object)
      : {}),
  },
  submitMain: { fontSize: 15, fontWeight: '700', color: IOS_COLORS.label },
  submitSub: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 2 },
  submitHint: { fontSize: 13, color: IOS_COLORS.labelTertiary },
  submitBlockHint: {
    fontSize: 12,
    color: IOS_COLORS.red,
    marginTop: 6,
    lineHeight: 17,
    fontWeight: '500',
  },
  submitBtn: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: IOS_COLORS.blue,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 104,
    flexShrink: 0,
  },
  submitBtnRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  submitBtnSecondary: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: IOS_COLORS.fillMedium,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: IOS_COLORS.separatorLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitBtnSecondaryDisabled: { opacity: 0.45 },
  submitBtnSecondaryText: { color: IOS_COLORS.label, fontSize: 14, fontWeight: '600' },
  submitBtnDisabled: { backgroundColor: IOS_COLORS.labelTertiary },
  submitBtnText: { color: '#fff', fontSize: 15, fontWeight: '700', lineHeight: 15 },

  toast: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 80,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(52,199,89,0.94)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  toastText: { color: '#fff', fontSize: 14, fontWeight: '600', flex: 1 },
  toastLink: { color: '#fff', fontSize: 13, fontWeight: '700', textDecorationLine: 'underline' },
});
