import { StyleSheet } from 'react-native';
import { IOS_COLORS } from '../../theme/paperTheme';

/** 主屏：Tab / 总览列表 / Toast */
export const orderScreenStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: IOS_COLORS.systemGrouped },

  tabBar: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 14,
    padding: 5,
    gap: 4,
    marginHorizontal: 12,
    marginTop: 4,
    marginBottom: 10,
  },
  tabItem: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingVertical: 9,
    paddingHorizontal: 2,
    borderRadius: 10,
  },
  tabItemDense: {
    paddingVertical: 7,
    gap: 2,
  },
  tabItemActive: {
    backgroundColor: IOS_COLORS.blueLight,
  },
  tabLabel: { fontSize: 13, color: IOS_COLORS.labelSecondary, fontWeight: '600', textAlign: 'center' },
  tabLabelDense: { fontSize: 11, lineHeight: 14, fontWeight: '600' },
  tabLabelActive: { color: IOS_COLORS.blue, fontWeight: '700' },
  pageMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: -2,
    marginBottom: 8,
    gap: 10,
  },
  pageMetaText: {
    fontSize: 13,
    color: IOS_COLORS.labelSecondary,
    fontWeight: '500',
  },
  overviewDateCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(17,17,17,0.08)',
    padding: 10,
    gap: 8,
  },
  overviewDateQuickRow: { flexDirection: 'row', gap: 8 },
  overviewDateQuick: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: IOS_COLORS.fillLight,
  },
  overviewDateQuickActive: {
    backgroundColor: IOS_COLORS.blueLight,
  },
  overviewDateQuickText: {
    fontSize: 12,
    color: IOS_COLORS.labelSecondary,
    fontWeight: '600',
  },
  overviewDateQuickTextActive: {
    color: IOS_COLORS.blue,
  },
  limitRowInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  limitLabel: { fontSize: 12, color: IOS_COLORS.labelSecondary },
  limitChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: IOS_COLORS.fillLight,
  },
  limitChipActive: { backgroundColor: IOS_COLORS.blueLight },
  limitChipText: { fontSize: 12, color: IOS_COLORS.labelSecondary, fontWeight: '600' },
  limitChipTextActive: { color: IOS_COLORS.blue },

  /** 总览双行汇总容器 */
  summaryCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(17,17,17,0.08)',
    overflow: 'hidden',
  },
  summaryBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  summaryInCardDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(0,0,0,0.08)',
    marginHorizontal: 10,
  },
  summaryItem: { flex: 1, alignItems: 'center', gap: 2 },
  summaryValue: { fontSize: 18, fontWeight: '700' },
  summaryLabel: { fontSize: 12, color: IOS_COLORS.labelSecondary },
  summaryDivider: { width: StyleSheet.hairlineWidth, backgroundColor: 'rgba(0,0,0,0.08)', marginVertical: 4 },
  summaryHint: {
    marginTop: -2,
    marginBottom: 8,
    marginHorizontal: 16,
    fontSize: 12,
    color: IOS_COLORS.labelSecondary,
    lineHeight: 17,
  },

  filterSection: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  segmentedBar: {
    flexDirection: 'row',
    backgroundColor: 'rgba(118,118,128,0.12)',
    borderRadius: 10,
    padding: 2,
  },
  segment: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 7,
    borderRadius: 8,
  },
  segmentActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  segmentText: { fontSize: 13, color: IOS_COLORS.labelSecondary, fontWeight: '500' },
  segmentTextActive: { color: IOS_COLORS.label, fontWeight: '600' },

  pillRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6 },
  pillGap: { flexBasis: '100%', height: 0 },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  pillStatusActive: { backgroundColor: '#34C759' },
  pillTypeActive: { backgroundColor: '#FF9500' },
  pillText: { fontSize: 12, color: IOS_COLORS.labelSecondary, fontWeight: '500' },
  pillTextActive: { color: '#fff', fontWeight: '600' },

  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginTop: 4,
  },
  sectionHeaderTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: IOS_COLORS.labelSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  sectionCount: { fontSize: 13, color: IOS_COLORS.labelSecondary },

  orderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: 16,
    marginHorizontal: 12,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(17,17,17,0.08)',
  },
  orderRowLast: {},
  orderAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  orderAvatarText: { fontSize: 18, fontWeight: '600', color: IOS_COLORS.blue },
  orderContent: { flex: 1, gap: 3, minWidth: 0 },
  /** 总览：姓名 + 状态，元信息单行化见 orderMetaLine */
  orderTop: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'nowrap' },
  orderName: { flex: 1, fontSize: 15, fontWeight: '600', color: IOS_COLORS.label, minWidth: 0 },
  hospitalBadge: { backgroundColor: IOS_COLORS.blueLight, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  hospitalText: { fontSize: 11, color: IOS_COLORS.blue, fontWeight: '600' },
  statusBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, flexShrink: 0 },
  statusText: { fontSize: 11, fontWeight: '600' },
  deliveryFailedBadge: {
    backgroundColor: '#FDECEC',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  deliveryFailedText: { fontSize: 11, color: '#D97A00', fontWeight: '700' },
  orderMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  /** 总览列表：替代多枚小 tag，用「 · 」串起同一信息 */
  orderMetaLine: {
    fontSize: 12,
    lineHeight: 16,
    color: IOS_COLORS.labelSecondary,
    marginTop: 1,
  },
  /** 本单点餐份数（高亮） */
  orderMetaQty: {
    fontSize: 14,
    fontWeight: '800',
    color: IOS_COLORS.blue,
  },
  cardTag: {
    fontSize: 12,
    color: IOS_COLORS.labelSecondary,
    backgroundColor: IOS_COLORS.fillLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  remainingTag: {
    fontSize: 12,
    color: IOS_COLORS.blue,
    backgroundColor: IOS_COLORS.blueLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: '600',
  },
  noCardTag: {
    fontSize: 12,
    color: IOS_COLORS.red,
    backgroundColor: '#FFE5E5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: '600',
  },
  adhocTag: { fontSize: 12, color: '#FF9500', backgroundColor: '#FFF4E5', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  giftTag: { fontSize: 12, color: '#AF52DE', backgroundColor: '#F5EEFB', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, fontWeight: '600' },
  staffMealTag: { fontSize: 12, color: '#007AFF', backgroundColor: '#E8F4FC', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, fontWeight: '600' },
  orderQty: { fontSize: 14, fontWeight: '600', color: IOS_COLORS.label },
  proofPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: IOS_COLORS.blueLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  proofPillText: { fontSize: 11, fontWeight: '700', color: IOS_COLORS.blue },
  orderNote: { fontSize: 13, color: IOS_COLORS.orange, lineHeight: 18 },
  orderNoteLabel: { fontWeight: '700' },
  rowChevron: { marginLeft: 4 },

  empty: { alignItems: 'center', paddingTop: 80, gap: 12 },
  emptyText: { fontSize: 16, color: IOS_COLORS.labelSecondary },
  emptyLink: { fontSize: 16, color: IOS_COLORS.blue },

  errorToast: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,59,48,0.94)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  errorToastText: { color: '#fff', fontSize: 14, fontWeight: '600', flex: 1 },
  errorToastLink: { color: '#fff', fontSize: 13, fontWeight: '700', textDecorationLine: 'underline' },

  loadingToast: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  loadingToastText: { color: IOS_COLORS.labelSecondary, fontSize: 14 },
});
