import { StyleSheet } from 'react-native';
import { IOS_COLORS } from '../../theme/paperTheme';

export const prepDeliveryStyles = StyleSheet.create({
  scroll: { paddingHorizontal: 12, paddingBottom: 32 },

  summary: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  summaryTile: {
    flex: 1,
    borderRadius: 14,
    padding: 14,
    gap: 2,
  },
  summaryLabel: { fontSize: 12, color: IOS_COLORS.labelSecondary, fontWeight: '500' },
  summaryValue: { fontSize: 28, fontWeight: '700', letterSpacing: -0.5, lineHeight: 32 },
  summaryUnit: { fontSize: 14, fontWeight: '500' },
  summarySub: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 2 },

  mealBlock: { marginBottom: 18 },
  mealHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingVertical: 6,
  },
  mealTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: IOS_COLORS.labelSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  mealCount: { fontSize: 13, color: IOS_COLORS.labelSecondary },

  card: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 14,
    marginBottom: 10,
    overflow: 'hidden',
    minHeight: 92,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(17,17,17,0.08)',
  },
  cardBody: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    alignItems: 'flex-start',
  },
  cardContent: { flex: 1, gap: 4 },
  cardAvatarLg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  cardAvatarTextLg: { fontSize: 18, fontWeight: '700', color: IOS_COLORS.blue },

  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  cardName: { fontSize: 16, fontWeight: '700', color: IOS_COLORS.label },
  cardNameLink: { color: IOS_COLORS.blue },
  nameLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginRight: 2,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 1,
  },
  infoText: {
    flex: 1,
    fontSize: 13,
    color: IOS_COLORS.label,
    fontWeight: '500',
  },
  infoTextMuted: {
    color: IOS_COLORS.labelTertiary,
    fontWeight: '400',
  },
  cardMetaDim: {
    fontSize: 11,
    color: IOS_COLORS.labelTertiary,
    marginTop: 2,
  },

  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  mealTypePill: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  mealTypePillLunch: { backgroundColor: '#FFF4E5' },
  mealTypePillDinner: { backgroundColor: '#F5E9FC' },
  mealTypePillText: { fontSize: 11, fontWeight: '700' },
  mealTypePillTextLunch: { color: '#FF9500' },
  mealTypePillTextDinner: { color: '#AF52DE' },
  qtyPill: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: IOS_COLORS.fillLight,
  },
  qtyPillText: {
    fontSize: 11,
    color: IOS_COLORS.label,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  cardMeta: { fontSize: 13, color: IOS_COLORS.labelSecondary, fontWeight: '500' },

  tag: {
    backgroundColor: IOS_COLORS.blueLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  tagText: { fontSize: 11, fontWeight: '700', color: IOS_COLORS.blue },

  noteBox: {
    marginTop: 3,
    backgroundColor: '#FFF8E6',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 2,
  },
  noteText: { fontSize: 12, color: '#8A5A00', lineHeight: 16 },
  noteLabel: { fontWeight: '700' },

  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addressText: { flex: 1, fontSize: 15, color: IOS_COLORS.label, fontWeight: '600', lineHeight: 20 },

  sideConfirm: {
    width: 68,
    backgroundColor: IOS_COLORS.blue,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 4,
    paddingVertical: 8,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: 'rgba(255,255,255,0.35)',
  },
  sideConfirmText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 15,
    letterSpacing: 0.2,
  },
  deliveryFailedBtn: {
    marginTop: 4,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFF4E5',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  deliveryFailedBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: IOS_COLORS.red,
  },

  empty: { alignItems: 'center', paddingVertical: 60, gap: 10 },
  emptyTitle: { fontSize: 17, fontWeight: '700', color: IOS_COLORS.label },
  emptySub: { fontSize: 13, color: IOS_COLORS.labelSecondary },
});
