import { StyleSheet } from 'react-native';
import { IOS_COLORS } from '../../theme/paperTheme';

export const statusSheetStyles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  sheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  sheetCard: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    paddingBottom: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: IOS_COLORS.fillMedium,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 10,
  },

  orderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginHorizontal: 10,
    marginBottom: 8,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.06)',
    gap: 10,
  },
  orderInfoLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  orderAvatarPress: { position: 'relative' },
  orderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  orderAvatarLink: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 1,
  },
  orderAvatarText: { fontSize: 16, fontWeight: '700', color: IOS_COLORS.blue },
  orderName: { fontSize: 16, fontWeight: '600', color: IOS_COLORS.label },
  orderSub: { fontSize: 13, color: IOS_COLORS.labelSecondary, marginTop: 2 },
  curStatusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  curStatusText: { fontSize: 12, fontWeight: '600' },

  proofBlock: {
    marginHorizontal: 10,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(0,122,255,0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,122,255,0.2)',
  },
  proofBlockTitle: { fontSize: 14, fontWeight: '700', color: IOS_COLORS.label },
  proofBlockHint: { fontSize: 12, color: IOS_COLORS.labelSecondary, marginTop: 4, marginBottom: 8 },
  proofStrip: { flexDirection: 'row', gap: 8, paddingVertical: 4 },
  proofThumbWrap: {
    width: 72,
    height: 72,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: IOS_COLORS.fillLight,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  proofThumb: { width: '100%', height: '100%' },

  lightboxBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  lightboxImage: { width: '100%', height: '100%', maxWidth: 420 },

  notesRow: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginHorizontal: 10,
    marginBottom: 4,
    borderRadius: 12,
    backgroundColor: '#FFF8E6',
  },
  notesText: { fontSize: 13, color: '#8A5A00', lineHeight: 18 },
  notesLabel: { fontWeight: '700' },

  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: IOS_COLORS.labelSecondary,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },

  statusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  statusBtn: {
    flex: 1,
    minWidth: 130,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1.5,
  },
  statusBtnCurrent: { borderWidth: 2 },
  statusBtnIcon: {},
  statusBtnLabel: { fontSize: 14, fontWeight: '600' },
  closeBtn: {
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: 'rgba(118,118,128,0.12)',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  closeBtnText: { fontSize: 17, color: IOS_COLORS.label, fontWeight: '600' },
});
